### ISSUE TITLE
Self-Organizing Maps in Scikit Learn

### ISSUE THREAD

**Issue by sarwatfatimam** [justmarkham/scikit-learn-videos#1]
Hello! 

First of all, thankyou so much for this series and all the resources you have mentioned with them. I started out with machine learning a few months ago and after reading, searching online, I was still not able to grasp the core of the machine learning. Your videos made it really simple and easy to understand! Most of my confusions cleared up! I hope you keep making these videos. 

Anyways, Can you please make or refer me a video tutorial or great resource on Self-Organizing Maps in Scikit Learn? It will be a great help! 

Thankyou again!

**Comment by justmarkham** [comment]
@Sarwat-Fatima Thanks for your kind comments! I really appreciate it.

I'm sorry, I'm not familiar with self-organizing maps, and so I can't be of help in this case.

Best of luck in your learning journey!
