### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by Machiner123** [justmarkham/scikit-learn-videos#10]
the line 

` print('{:^9} {} {:^25}'.format(iteration, data[0], data[1]))`

gives a type error

` print('{:^9} {} {:^25}'.format(iteration, data[0], str(data[1])))`

solves the problem

**Comment by justmarkham** [comment]
Thanks, I appreciate it! I'll fix it the next time I'm updating the notebooks.

**Comment by justmarkham** [comment]
@Machiner123 I know this is long overdue, but I just updated the notebooks, and I appreciate your solution to this particular error.
