### ISSUE TITLE
headers in Advertising.csv have changed

### ISSUE THREAD

**Issue by justmarkham** [justmarkham/scikit-learn-videos#13]

**Comment by ghost** [comment]
`sns.pairplot(data, x_vars=['TV', 'Radio', 'Newspaper'], y_vars='Sales', size)` ->
`sns.pairplot(data, x_vars=['TV', 'radio', 'newspaper'], y_vars='sales', size)`

**Comment by justmarkham** [comment]
@georgsh Thanks for letting me know! After I published the notebooks, the host of the original CSV file changed the CSV headers as you noted.

I resolved this by obtaining a copy of the original data file and added it to the repo (in the data subdirectory), and then pointed the notebooks to that file.
