### ISSUE TITLE
in 09_classification_metrics

### ISSUE THREAD

**Issue by BMeridian** [justmarkham/scikit-learn-videos#3]
running this:
## examine the class distribution of the testing set (using a Pandas Series method)

y_test.value_counts()

I get this:

AttributeError                            Traceback (most recent call last)
<ipython-input-29-a75c8fa7d351> in <module>()
      1 # examine the class distribution of the testing set (using a Pandas Series method)
----> 2 y_test.value_counts()

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

**Comment by justmarkham** [comment]
Somewhat recently, scikit-learn changed `train_test_split` so that it would return Pandas objects (if given a Pandas object). Previous to that, `train_test_split` always returned NumPy arrays.

What version of scikit-learn are you using? The current version is 0.16.
