### ISSUE TITLE
Error: 'unable to contact kernel' on Jupyter 3.2.x +

### ISSUE THREAD

**Issue by brylie** [justmarkham/scikit-learn-videos#6]
When running these notebooks on Jupyter 3.2.x or 4.2.x, I get the following error:

> Failed to start the kernel
> 
> The 'None' kernel is not available. Please pick another suitable kernel instead, or install that kernel.

Note, the Kernel is running when I create a new notebook, so the problem seems to be related to incompatibility between these notebooks and Jupyter.
# Environment
## localhost

Here is  my local Environment:

> The version of the notebook server is 4.2.1 and is running on:
> 
> Python 3.5.1 |Anaconda 4.1.0 (64-bit)| (default, Jun 15 2016, 15:32:45) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
> 
> Current Kernel Information:
> 
> unable to contact kernel
## mybinder.org

> The version of the notebook server is 3.2.0-8b0eef4 and is running on:
> 
> Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

**Comment by brylie** [comment]
I just realized that the Kernel is not running in any of the notebooks from this repository:

> Failed to start the kernel

> The 'None' kernel is not available. Please pick another suitable kernel instead, or install that kernel.

Here is  my local Environment:

Server Information:

> The version of the notebook server is 4.2.1 and is running on:

> Python 3.5.1 |Anaconda 4.1.0 (64-bit)| (default, Jun 15 2016, 15:32:45) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

>Current Kernel Information:

> unable to contact kernel

Note, the Kernel is running when I create a new notebook, so the problem seems to be related to incompatibility between these notebooks and Jupyter.

**Comment by justmarkham** [comment]
I'm updating the notebooks later this week and will let you know what I find out. Thanks!

**Comment by justmarkham** [comment]
@brylie I just updated the notebooks today. Hopefully that resolves the issue, but please let me know if the issue persists!
